{"name": "Проверка получения ответа об успешном принятии заказа", "status": "passed", "statusDetails": {"message": "AssertionError: assert '{\"ok\":true}' in '{\"code\":404,\"message\":\"Заказа с таким id не существует\"}'\n +  where '{\"code\":404,\"message\":\"Заказа с таким id не существует\"}' = <Response [404]>.text", "trace": "self = <tests.test_take_order.TestTakeOrder object at 0x10294b050>\n\n    @allure.title('Проверка получения ответа об успешном принятии заказа')\n    def test_take_order(self):\n        helper = Helpers()\n        order = helper.create_order()\n        response = requests.post(Constants.url_order, data=order)\n        id_order = response.json()[\"track\"]\n        courier = helper.authorization_with_required_fields()\n        response_post = requests.post(Constants.url_authorization, data=courier)\n        id_courier = response_post.json()['id']\n        response_put = requests.put(f\"{Constants.url_take_order}{id_order}?courierId={id_courier}\")\n>       assert '{\"ok\":true}' in response_put.text\nE       assert '{\"ok\":true}' in '{\"code\":404,\"message\":\"Заказа с таким id не существует\"}'\nE        +  where '{\"code\":404,\"message\":\"Заказа с таким id не существует\"}' = <Response [404]>.text\n\ntests/test_take_order.py:21: AssertionError"}, "start": 1706633039188, "stop": 1706633040912, "uuid": "2b9fbaf1-0b37-4146-9ebe-2f898c37a432", "historyId": "e575ff5d2d58158d718089950c0cee8d", "testCaseId": "e575ff5d2d58158d718089950c0cee8d", "fullName": "tests.test_take_order.TestTakeOrder#test_take_order", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_take_order"}, {"name": "subSuite", "value": "TestTakeOrder"}, {"name": "host", "value": "MBP-Ilya.cn.ru_novotelecom.ru"}, {"name": "thread", "value": "16501-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_take_order"}]}